### PR TITLE
Use new proc type function declaration for Date.fromIsoString().

### PR DESCRIPTION
**Pull request by thomasvandoren**
Also...
- Declare Date.min and Date.max as pseudo-attributes using the paren-less proc
  type function declaration.
- Update solution 19 to use Date.fromIsoString() correctly.
- Update solutions 5, 7, 8, 12, and 23 to work with some changes to compiler. Most
  were due to improved const-ness checking on arrays and the new form is better anyway.
- Shuffle test scripts and add some make targets that allow for travis testing.
- Add .travis.yml file so tests will run automatically in travis.

Requires https://github.com/chapel-lang/chapel/pull/2106 for lib/Date.chpl changes.

### CODE REVIEW

**Comment by bradcray** [comment]
I've now been pointed to Project Euler by three people w.r.t. Chapel in 24 hours.  Coincidence?  Here's one of the others:  https://github.com/briangu/cheuler

**Comment by thomasvandoren** [comment]
3 people! Wow. According the Project Euler site, 4 people use Chapel to solve problems and on average they have provided solutions for 5% of the problems:

language stats

**Comment by bradcray** [comment]
Huh... all of those percentages seem low.  How many problems are there?  (I was thinking a dozen or two?)

**Comment by thomasvandoren** [comment]
There are 521 problems. They are releasing new ones weekly, I believe--#521 was released on Jun-20. For me, they get a lot more challenging mathematically as I progress. Completing the next 30 problems will probably be much more difficult than the first 30.

**Pull request merged**
